### ISSUE TITLE
Usage on windows with integrated command

### ISSUE THREAD

**Issue by davejal** [liebig/cron#52]
Hi,

this is not really an issue, but rather some help I need that I couldn't find in the documentation.

I'm missing info on how to use this on windows.
using git bash and typing in the url rout (http: //localhost:800/cron/run/key) my command runs correctly. Now the cron (setup to run automaticlly) is giving me problems.

is it possible to run on windows and what are my next steps? I rather not use the windows task manager to run a batch file.

Note1: from the git bash in the root folder I ran ' * * * * * php artisan cron:run ' but get an error (it reads ./contributing.md from the root folder), so I'm doing something wrong there

Note2: running ' php artisan cron:list ' I get an emtpy list (table)

**Comment by davejal** [comment]
Installed on linux as I didn't get an answer

both commands are working fine now

**Comment by liebig** [comment]
Hi davejal,

Thanks for using Cron. You can use the Windows [AT command](http://ss64.com/nt/at.html), install [CRONw](http://cronw.sourceforge.net/) or use [crontab in Cygwin](http://stackoverflow.com/questions/707184/how-do-you-run-a-crontab-in-cygwin-on-windows). I would prefer Cygwin because it brings many Linux tools to Windows.

Please note that I develop and support Cron in my free time. I don't earn any money with this. So please be a little bit more patient with receiving free support from me.

Thank you,
Marc Liebig

**Comment by davejal** [comment]
Hi Liebig,

I was glad to be able to use something you wrote, I just didn't want to
waste your perfect time for something I already did on linux (as I have
linux knowledge to).

Sorry If I seemed to rush you for a response.

Thanks for all.

regards,

Dave

**Comment by davejal** [comment]
Hi Liebig,

I have one small question:
"How could I troubleshoot if something isn't working as it's supposed to?"

I wrote a small cron to mail me some info out of a db every night, but I receive the mails double. I have to say I fumbled a lot with the cron->controller->route->command before I finally got to something working, but I think I removed all other references to this mail function. Were would you start debugging and how?

regards,

Dave

p.s. I'm working on debian 7 with laravel 4.2

**Comment by liebig** [comment]
Hi Dave,

Have a look at the `cron_manager` and `cron_job` database tables. If you find more than one entry in the `cron_manager` table for your defined time interval, you probably execute `Cron` too often. If you find more than one entry in the `cron_job` table for a manager id, your probably call your send-mail-function too often. Otherwise have a look at your send-mail-function. Maybe it sends the mail twice?

Best Regards,
Marc
