### ISSUE TITLE
How can I Install liebig/cron on lumen

### ISSUE THREAD

**Issue by kdszh** [liebig/cron#68]
Hi,
     Is there any installation guide for lumen ,I just found Laravel 5 Installation step,and have some trouble in moving cron to lumen. thanks.

**Comment by liebig** [comment]
Hi,
Cron does not support Lumen at the moment. I will check if it is possible to get Cron running with it.

**Comment by kdszh** [comment]
Thanks for reply.

by the way,is it easy to migrate Cron to Lumen by modify some files and structures ?

**Comment by liebig** [comment]
Hi @kdszh,
Sorry for the late reply, but I did not forget you ;) The short bad news is that I have to rewrite parts of Cron to work with Lumen and at the moment I will not do this.

The long answer is, that I had a hard time with Lumen. After installation nothing worked. I installed Lumen on Windows and Ubuntu. It does not work. After asking the community I got the answer, that I have to change `$app->run();` to `$app->run($app['request']);`. But I got no answer why I have to change this Lumen core function. After this change Lumen worked. The next problem was Lumens configuration: `Unlike the full-stack Laravel framework which has multiple configuration files, all of the configuration options for the Lumen framework are stored in a single .env configuration file.`. So I have to change Crons configuration behaviour. This is a big deal, because Cron uses Laravels configuration class very often. But the biggest deal for me is, that I think Lumen is not production ready yet.

Because of this I will not rewrite Cron for Lumen at the moment and I will close this issue. But feel free to reopen this ticket if a new major release of Lumen was published.

I hope you understand my decision :)
Thank you
Marc
