### ISSUE TITLE
How can I call Cron:: outside of global.php

### ISSUE THREAD

**Issue by blaxroze** [liebig/cron#71]
I hv an app, every user can create a campaign and will run 2 php files every 2 minutes.
How can I use Cron:: outside global.php?

**Comment by liebig** [comment]
Thanks for using Cron. I don't undertsand why you want to use Cron outise the `global.php` file? The problem is, that you cannot add jobs to Cron somewhere in your code and expect that this jobs will be executed the next time `Cron::run()` is called. After adding a job the Cron somewhere in the code and after sending the response to the client, the PHP garbage collector will delete all classes. And if the time has come and `Cron::run()` get called (for example every minute) the added job is already deleted from memory. So you need something like a database. Everytime a user creates a campaign, add a new entry to the database. In your `global.php` run through this table and add a job to Cron:
```php
\Cron::add('jobFromDatabase1', '* * * * *', function() {
                    // Do some crazy things successfully every minute
                    return null;
                });
```
For security reasons, I would not recommend to add the PHP function from database. So define your function for each job in the `global.php` file, add a job for every database entry and after all run `Cron::run()`.

Thanks for using Cron. I don't undertsand why you want to use Cron outise the `global.php` file? The problem is, that you cannot add jobs to Cron somewhere in your code and expect that this jobs will be executed the next time `Cron::run()` is called. After adding a job the Cron somewhere in the code and after sending the response to the client, the PHP garbage collector will delete all classes. And if the time has come and `Cron::run()` get called (for example every minute) the added job is already deleted from memory. So you need something like a database. Everytime a user creates a campaign, add a new entry to the database. In your `global.php` run through this table and add a job to Cron:
```php
\Cron::add('jobFromDatabase1', '* * * * *', function() {
                    // Do some crazy things successfully every minute
                    return null;
                });
```
For security reasons, I would not recommend to add the PHP function from database. So define your function for each job in the `global.php` file, add a job for every database entry and after all run `Cron::run()`.

I hope it helps.

**Comment by blaxroze** [comment]
I see. I got it.
Because I want to add the job dynamically.

**Comment by liebig** [comment]
Yes. If you have another question, don't hasitate to open a new issue.
