### ISSUE TITLE
usage question: loading jobs from database

### ISSUE THREAD

**Issue by larsbo** [liebig/cron#81]
I'm using the package in a project for some time now and it works fine. However, from time to time some  changes to the scheduling are necessary or another job have to be added in the project. I wonder if you can make the process more dynamic by loading the jobs from database instead of defining them inside the code.
Is this possible or are there any side effects of this approach?

**Comment by liebig** [comment]
There are two options to load jobs from database. The first option is to load the cron expression and the function from database. In my opinion this is a bad idea because someone with database access can easily manipulate the whole application. Your database schema could look like:
```php
Schema::create('jobs', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('expression');
    $table->string('function');
    $table->boolean('enabled');
});
```
After creating the Eloquent model `Job` class file for the jobs table you could add all cron jobs in the `AppServiceProvider.php` file like this:
```php
public function boot() {
    \Event::listen('cron.collectJobs', function() {

        $jobs = App\Job::all();

        foreach ($jobs as $job) {
            \Cron::add($job->name, $job->expression, function() {
                eval($job->function)
            }, $job->enabled);
        }
    });
}
```

The second and safer way is to load only the expression from database.
```php
Schema::create('jobs', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('expression');
    $table->boolean('enabled');
});
```

```php
public function boot() {
    \Event::listen('cron.collectJobs', function() {

        $example1 = App\Job::where('name', 'example1')->firstOrFail();

        \Cron::add('example1', $example1->expression, function() {
                // Do some crazy things successfully
                return null;
            }, $job->enabled);
    });
}
```

The code is not tested but I hope you get the concept. I prefer the second solution although it is not as dynamic as the first one.

**Comment by larsbo** [comment]
Thank you very much for the detailed answer!

Your security concerns are a very good point, too. I thought about that and I think with a function whitelist you can have a compromise between the two options.

**Comment by liebig** [comment]
Yes, I whitelist is maybe a good choice.
